// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADUzVtyv2rSRhrgzGqOhOr6eyxWDtAno0',
    appId: '1:1065002950803:web:4bc97c0eb9780e14c66d66',
    messagingSenderId: '1065002950803',
    projectId: 'appflutter-test',
    authDomain: 'appflutter-test.firebaseapp.com',
    storageBucket: 'appflutter-test.appspot.com',
    measurementId: 'G-DJT0C83PNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ2GnwcKvTcVa6T2-7jYB1W_klMtIk5AI',
    appId: '1:1065002950803:android:b8137bc8f0cdfa25c66d66',
    messagingSenderId: '1065002950803',
    projectId: 'appflutter-test',
    storageBucket: 'appflutter-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2MYI5ZRuFp0NkVrtxlk-klUJ5_cLnNoM',
    appId: '1:1065002950803:ios:e73f7c6f7634e7b6c66d66',
    messagingSenderId: '1065002950803',
    projectId: 'appflutter-test',
    storageBucket: 'appflutter-test.appspot.com',
    iosBundleId: 'com.example.intento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2MYI5ZRuFp0NkVrtxlk-klUJ5_cLnNoM',
    appId: '1:1065002950803:ios:e73f7c6f7634e7b6c66d66',
    messagingSenderId: '1065002950803',
    projectId: 'appflutter-test',
    storageBucket: 'appflutter-test.appspot.com',
    iosBundleId: 'com.example.intento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADUzVtyv2rSRhrgzGqOhOr6eyxWDtAno0',
    appId: '1:1065002950803:web:60d3ec5b557c5787c66d66',
    messagingSenderId: '1065002950803',
    projectId: 'appflutter-test',
    authDomain: 'appflutter-test.firebaseapp.com',
    storageBucket: 'appflutter-test.appspot.com',
    measurementId: 'G-T0GH5DJ2GQ',
  );
}
